pipeline {
    agent any
    
    environment {
        // GitHub configuration
        GITHUB_TOKEN = credentials('github-token')
        REPO_OWNER = 'panchalnihar'
        REPO_NAME = 'jenkins-pr-automation'
        BASE_BRANCH = 'main'
        FEATURE_BRANCH = "auto-pr-${BUILD_NUMBER}"
        
        // Git user configuration
        GIT_AUTHOR_NAME = 'Panchal Nihar'
        GIT_AUTHOR_EMAIL = 'panchalnihar18@gmail.com'
    }
    
    parameters {
        string(name: 'PR_TITLE', defaultValue: 'Automated PR', description: 'Pull Request Title')
        text(name: 'PR_BODY', defaultValue: 'This PR was automatically generated', description: 'PR Description')
        string(name: 'TARGET_BRANCH', defaultValue: 'main', description: 'Target branch for PR')
    }
    
    stages {
        stage('Checkout Repository') {
            steps {
                script {
                    echo "=== Stage 1: Checking out repository ==="
                    // Clean workspace and clone repository
                    checkout scm
                    sh """
                        git config user.name "${GIT_AUTHOR_NAME}"
                        git config user.email "${GIT_AUTHOR_EMAIL}"
                    """
                }
            }
        }
        
        stage('Create Feature Branch') {
            steps {
                script {
                    echo "=== Stage 2: Creating feature branch ${FEATURE_BRANCH} ==="
                    sh """
                        git checkout -b ${FEATURE_BRANCH}
                        echo "Branch created at: \$(date)" >> auto-generated.txt
                    """
                }
            }
        }
        
        stage('Make Automated Changes') {
            steps {
                script {
                    echo "=== Stage 3: Making automated changes ==="
                    // Example: Update a file with build info
                    sh """
                        echo "Build Number: ${BUILD_NUMBER}" >> build-info.txt
                        echo "Build Date: \$(date)" >> build-info.txt
                        echo "Branch: ${FEATURE_BRANCH}" >> build-info.txt
                        
                        # Add your custom automation logic here
                        # e.g., code generation, dependency updates, etc.
                    """
                }
            }
        }
        
        stage('Commit Changes') {
            steps {
                script {
                    echo "=== Stage 4: Committing changes ==="
                    sh """
                        git add .
                        git commit -m "chore: Automated changes from Jenkins build #${BUILD_NUMBER}" || echo "No changes to commit"
                    """
                }
            }
        }
        
        stage('Push to GitHub') {
            steps {
                script {
                    echo "=== Stage 5: Pushing to GitHub ==="
                    withCredentials([usernamePassword(credentialsId: 'github-credentials', 
                                                      passwordVariable: 'GIT_PASSWORD', 
                                                      usernameVariable: 'GIT_USERNAME')]) {
                        sh """
                            git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${REPO_OWNER}/${REPO_NAME}.git ${FEATURE_BRANCH}
                        """
                    }
                }
            }
        }
        
        stage('Create Pull Request') {
            steps {
                script {
                    echo "=== Stage 6: Creating Pull Request ==="
                    // Use GitHub API to create PR
                    def response = sh(script: """
                        curl -X POST \
                        -H "Authorization: token ${GITHUB_TOKEN}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls \
                        -d '{
                            "title": "${params.PR_TITLE} - Build #${BUILD_NUMBER}",
                            "body": "${params.PR_BODY}\\n\\nGenerated by Jenkins Build #${BUILD_NUMBER}",
                            "head": "${FEATURE_BRANCH}",
                            "base": "${params.TARGET_BRANCH}"
                        }'
                    """, returnStdout: true)
                    
                    echo "GitHub API Response: ${response}"
                    
                    // Parse PR number from response
                    def prNumber = sh(script: "echo '${response}' | grep -o '\"number\":[0-9]*' | grep -o '[0-9]*'", returnStdout: true).trim()
                    echo "✅ Pull Request #${prNumber} created successfully!"
                }
            }
        }
    }
    
    post {
        success {
            echo '✅ Pipeline completed successfully! PR has been created.'
        }
        failure {
            echo '❌ Pipeline failed. Check logs for details.'
        }
        cleanup {
            cleanWs()
        }
    }
}
